// <auto-generated />
namespace AdCenter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_default_tier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_default_tier));
        
        string IMigrationMetadata.Id
        {
            get { return "201712140207223_add_default_tier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
